"""Everyday необязательные поля True

Revision ID: 02cfa499f730
Revises: 
Create Date: 2020-10-24 12:32:57.109700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cfa499f730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('everyday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_data', sa.Date(), nullable=False),
    sa.Column('day_news', sa.Text(), nullable=False),
    sa.Column('yesterday_balance', sa.Numeric(), nullable=True),
    sa.Column('day_balance', sa.Numeric(), nullable=True),
    sa.Column('day_rate', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wir_amount', sa.Numeric(), nullable=False),
    sa.Column('wir_text', sa.Text(), nullable=False),
    sa.Column('wir_dc', sa.Integer(), nullable=False),
    sa.Column('everyday_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['everyday_id'], ['everyday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiring')
    op.drop_table('everyday')
    # ### end Alembic commands ###
